//all reducers get two arguments, 
//the piece of state that this reducer is responsible for (ie any state that has been previously generated by this reducer), 
//and an action

export default function(state = null, action){ //ES6 syntatic sugar "default values" if state is undefined it is set to be null
	

	switch(action.type){
		case 'BOOK_SELECTED':
			return action.payload; 
	}

	return state 
}

//we must always return a non-undefined value. So this return statement handles the initial pageload in which no book had been selected